### ISSUE TITLE
building respec snapshots via github actions

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#329]
In an email on www-math [1]
@bert-github suggests we move to publishing respec snapshots rather than the live respec source processing

This is an issue to track discussion and/or implementation of this.

The above has links to the basic instructions [2]  and looking at recent W3C TR specs a simple live spec using this is minapp-widget [3]
which has source html in main branch `[main]req/index.html` and a github action workflow to put the respec processed document at `[gh-pages]/req/index.html`  with the latter being served by gh-pages.

I did some trials in my fork but (not toally surprisingly) hit errors

`Default branch and "GH_PAGES_BRANCH": "gh-pages" cannot be same.`

So.. I think if we are to do this we would need to switch to a new (say, `main`) branch and set that branch as the default for push, pull requests etc. then just use the gh-pages branch to serve the generated snapshots. (and people with forks would probably need to make similar adjustments to match)

If done as in the example above the generated index.html masks the edited version, so only the generated snapshot is visible. I (think?) If I understand the instructions correctly it would also be possible to generate the snapshot under a different name say `spec.html` or `mathml.html`  so that both the live draft and snapshot are visible.

But I'm not sure what we want (or which is easiest to integrate with Echidna for automated publishing to W3C TR space.

Currently the inline mathml (in mathml4) and WPT results (in mathml core) are only visible in respec souce views not in snapshots.

[1] https://lists.w3.org/Archives/Public/www-math/2022Apr/0015.html

[2] https://w3c.github.io/spec-prod/#deploy-to-github-pages

[3] https://github.com/w3c/miniapp-widget/blob/main/.github/workflows/auto-publish.yml

**Comment by xfq** [comment]
(FWIW, I just came across this thread and since I configured the miniapp-widget-req example above, I'd be happy to help if anything is needed!)

**Comment by xfq** [comment]
Personally I think it should make the loading performance better for a long spec like MathML, but I haven't tested it.

**Comment by davidcarlisle** [comment]
@xfq  thanks yes I noticed afterwards that it was your addition coincidentally just after you had made some comments on the spec here:-)

On a fork of mathml-core I got this working, but currently building off `main` then checking the built spec into `gh-pages`
that works as designed, but I think I want to serve both the respec live version and the snapshot, 

so

https://davidcarlisle.github.io/mathml-core/spec.html

is a snapshop of today's draft (built from `main`)

but that leaves a 5 year old relic as the view of the live document built from `gh-pages`

https://davidcarlisle.github.io/mathml-core/


The supplied respec workflow does not allow the `GH_PAGES_BRANCH` to be the source branch but (I assume) I can get the workflow to always re-sync gh-pages from main before doing anyhing else so I end up with spec.html being the snapshot and
index.html being the live copy (or maybe re-arrange so that index.html is the snapshot and src/index.html the source)


```
# https://w3c.github.io/spec-prod/#examples
# Create a file called .github/workflows/auto-publish.yml
name: CI
on:
  push:
    branches: [main]
jobs:
  main:
    name: Deploy to GitHub pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
          SOURCE: index.html
          DESTINATION: spec.html
          VALIDATE_MARKUP: false

```

**Comment by davidcarlisle** [comment]
I think I have this working now in my mathml-core fork

live respec version

https://davidcarlisle.github.io/mathml-core/


updated respec snapshot

https://davidcarlisle.github.io/mathml-core/spec.html

@xfq  Not sure if this git reset is too agressive? (the gh-pages branch is essentially only used as a device for gh-pages so resetting it to match main doesn't seem too bad?....)

```
# https://w3c.github.io/spec-prod/#examples
# Create a file called .github/workflows/auto-publish.yml
name: CI
on:
  push:
    branches: [main]
jobs:
  main:
    name: Deploy to GitHub pages
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v2
     - run: |
          git fetch
          git checkout gh-pages
          git reset main --hard
          git push -f
     - uses: w3c/spec-prod@v2
       with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
          SOURCE: index.html
          DESTINATION: spec.html
          VALIDATE_MARKUP: false
````

@ljmaher is 

https://davidcarlisle.github.io/mathml-core/spec.html

better for your screen reader than

https://davidcarlisle.github.io/mathml-core/

?
